package com.abc.salesinventory.model.newpackage;
// Generated Aug 11, 2014 2:22:10 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private String id;
     private String name;
     private String description;
     private Set<RolePermission> rolePermissions = new HashSet<RolePermission>(0);
     private Set<UserRole> userRoles = new HashSet<UserRole>(0);

    public Role() {
    }

    @Override
    public String toString() {
        return  name;
    }

	
    public Role(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Role(String id, String name, String description, Set<RolePermission> rolePermissions, Set<UserRole> userRoles) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.rolePermissions = rolePermissions;
       this.userRoles = userRoles;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set<RolePermission> getRolePermissions() {
        return this.rolePermissions;
    }
    
    public void setRolePermissions(Set<RolePermission> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }
    public Set<UserRole> getUserRoles() {
        return this.userRoles;
    }
    
    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }




}


