package com.abc.salesinventory.model.newpackage;
// Generated Aug 11, 2014 2:22:10 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private String transactionId;
     private Customer customer;
     private Supplier supplier;
     private Date date;
     private double total;
     private String transactionType;
     private String paymentMethod;
     private Set<TransactionDetail> transactionDetails = new HashSet<TransactionDetail>(0);

    public Transaction() {
    }
    
    @Override
    public String toString() {
        return transactionId;
    }
    
    public Transaction(String transactionId)
    { this.transactionId=transactionId;
    }

	
    public Transaction(String transactionId, Date date, double total, String transactionType, String paymentMethod) {
        this.transactionId = transactionId;
        this.date = date;
        this.total = total;
        this.transactionType = transactionType;
        this.paymentMethod = paymentMethod;
    }
    public Transaction(String transactionId, Customer customer, Supplier supplier, Date date, double total, String transactionType, String paymentMethod, Set<TransactionDetail> transactionDetails) {
       this.transactionId = transactionId;
       this.customer = customer;
       this.supplier = supplier;
       this.date = date;
       this.total = total;
       this.transactionType = transactionType;
       this.paymentMethod = paymentMethod;
       this.transactionDetails = transactionDetails;
    }
   
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Supplier getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public String getPaymentMethod() {
        return this.paymentMethod;
    }
    
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Set<TransactionDetail> getTransactionDetails() {
        return this.transactionDetails;
    }
    
    public void setTransactionDetails(Set<TransactionDetail> transactionDetails) {
        this.transactionDetails = transactionDetails;
    }




}


